apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: virt-controller-api-cert
  namespace: virtink-system
spec:
  issuerRef:
    kind: Issuer
    name: virt-controller-cert-issuer
  commonName: virt-controller.virtink-system.svc
  dnsNames:
    - virt-controller.virtink-system.svc
    - virt-controller.virtink-system.svc.cluster.local
  secretName: virt-controller-api-cert
