apiVersion: v1
kind: Service
metadata:
  name: virt-controller
  namespace: virtink-system
spec:
  selector:
    name: virt-controller
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
    - name: api
      port: 8443
      targetPort: 8443
